name: Publish package to GitHub Packages
on:
  release:
    types: [edited, preleased, published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@rfwatson'
      - run: pnpm install --frozen-lockfile
      - run: pnpm publish --filter @rfwatson/microdsp-web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
